<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1677" started-at="2021-11-26T20:55:24Z" finished-at="2021-11-26T20:55:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1677" started-at="2021-11-26T20:55:24Z" finished-at="2021-11-26T20:55:25Z">
      <class name="TestCasesOn_Fake_API">
        <test-method status="PASS" signature="TaskNum_One()[pri:1, instance:TestCasesOn_Fake_API@6e3c1e69]" name="TaskNum_One" duration-ms="1361" started-at="2021-11-26T22:55:24Z" finished-at="2021-11-26T22:55:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TaskNum_One -->
        <test-method status="PASS" signature="TaskNum_Two()[pri:2, instance:TestCasesOn_Fake_API@6e3c1e69]" name="TaskNum_Two" duration-ms="13" started-at="2021-11-26T22:55:25Z" finished-at="2021-11-26T22:55:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TaskNum_Two -->
        <test-method status="PASS" signature="TaskNum_Three()[pri:3, instance:TestCasesOn_Fake_API@6e3c1e69]" name="TaskNum_Three" duration-ms="50" started-at="2021-11-26T22:55:25Z" finished-at="2021-11-26T22:55:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TaskNum_Three -->
        <test-method status="PASS" signature="TaskNum_Four()[pri:4, instance:TestCasesOn_Fake_API@6e3c1e69]" name="TaskNum_Four" duration-ms="89" started-at="2021-11-26T22:55:25Z" finished-at="2021-11-26T22:55:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TaskNum_Four -->
        <test-method status="PASS" signature="TaskNum_Five()[pri:5, instance:TestCasesOn_Fake_API@6e3c1e69]" name="TaskNum_Five" duration-ms="55" started-at="2021-11-26T22:55:25Z" finished-at="2021-11-26T22:55:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TaskNum_Five -->
        <test-method status="FAIL" signature="TaskNum_Six()[pri:6, instance:TestCasesOn_Fake_API@6e3c1e69]" name="TaskNum_Six" duration-ms="89" started-at="2021-11-26T22:55:25Z" finished-at="2021-11-26T22:55:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [100] but found [910]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [100] but found [910]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at TestCasesOn_Fake_API.TaskNum_Six(TestCasesOn_Fake_API.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TaskNum_Six -->
      </class> <!-- TestCasesOn_Fake_API -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
